### ISSUE TITLE
Examples are a bit confusing

### ISSUE THREAD

**Issue by floriangaechter** [veith/flowbased-behaviour#5]
Maybe it would make sense to rephrase some of the examples:
```
<emmiting-component @-response="((responseFromSomewhere))"></emmiting-component>
<emmiting-component @-response="otherResponse"></emmiting-component>

<receiving-component ƒ-show-data="otherResponse"></receiving-component>
{{responseFromSomewhere}}
```
It's kind of confusing that the `<emmiting-component>` triggers a `response` method. Maybe it would be easier to understand if it triggered a more generic `@-somethingHappened` method (because emitting and response are somewhat conflicting words in this case). By the way, it's e**m**itting, not e**mm**itting ;-)

**Comment by veith** [comment]
Thank you for the input. The new documentation is available under https://veith.github.io/flowbased-polymer/  
I hope this helps.
